### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jcommander** [utilForever/DirectX#1]
Thank you for making this it fixed some errors, but I still get a lot
A lot of Macro redefinition warnings and syntax errors in dxgi1_2.h
I know it's because of two DirectX SDKs conflicting, but how do I remove one
I'm using Visual Studio 2013 Ultimate
Build Output:http://pastebin.com/8wzKYbp7

I really want to start reading this book.

**Comment by utilForever** [comment]
Hi, @killerjustin 

I'll check this issue and reply comment after solving it.

Thanks,
Chris.

**Comment by jcommander** [comment]
I fixed it, it was due to incorrect including as I followed the steps in the readme instead of using the code from here.

There you didn't mention that you had to include d3d11.h before d3dx11.h and that you have to include dxgi.h before too.

I have done this before but then it didn't work, maybe I did it wrong then, but now everything works fine!
Thank you so much, you have done a great job! There's not a lot of helpful stuff on the Internet about Frank Luna's Book in newer VS versions!

Sincerely,
Justin
